###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Tom van Woudenberg and Iuri Rocha from Delft University of Technology. Built with <a href="https://teachbooks.io">TeachBooks</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.extlinks', 'teachbooks_favourites', 'sphinx_tudelft_theme', 'sphinx_apa_references', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
html_baseurl = 'https://oit.tudelft.nl/CIEM5000/2026/'
html_favicon = ''
html_js_files = ['https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js']
html_logo = ''
html_show_copyright = False
html_sourcelink_suffix = ''
html_static_path = ['figures']
html_theme = 'sphinx_book_theme'
html_theme_options = {'logo': {'text': 'CIEM5000 - Matrix Method in statics'}, 'repository_url': 'https://github.com/TUDelft-books/CIEM5000', 'path_to_docs': 'book', 'repository_branch': '2026', 'use_edit_page_button': True, 'use_repository_button': True, 'use_issues_button': True, 'launch_buttons': {'thebe': True}, 'announcement': "<p>This book is not the version shared with students. That one is available here <a href='https://oit.tudelft.nl/CIEM5000/2026/' style='color: cyan;'>oit.tudelft.nl/CIEM5000/2026/</a></p>"}
html_title = 'Matrix Method in statics'
keep_warnings = True
latex_engine = 'pdflatex'
mathjax3_config = {'chtml': {'mtextInheritFont': True}, 'tex': {'macros': {'mrm': '\\mathrm', 'mymat[1]': '\\left[ \\begin{matrix} #1 \\end{matrix} \\right]'}}}
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
named_colors_custom_colors = {'cA': [1, 113, 136], 'cB': [195, 49, 47], 'cE': [0, 163, 144], 'cI': [235, 114, 70]}
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
thebe_config = {'use_thebe_lite': True, 'exclude_patterns': ['**/_*.yml', '**/*.md', '**/*.ipynb', '**/*.pdf', '**/*.svg', '**/*.jpg', '**/*.png', '**/*.vsdx', '**/*.bib', '**/*.zip']}
tud_change_titlesize = False
use_jupyterbook_latex = True
use_multitoc_numbering = True
